spring.application.name=uecs3563backend
spring.config.import=optional:file:.env[.properties]

# Enable the H2 database console UI for browser testing
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database connection credentials
spring.datasource.url=${H2DB_URL}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${H2DB_USERNAME}
spring.datasource.password=${H2DB_PASSWORD}

# JPA & Hibernate configuration to auto-load your schema and tables
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always